// Real ledger and CSRF on the isolated fixture server; no production mutations.
const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '../..');
const { chromium, expect } = require(path.join(root, 'frontend/node_modules/@playwright/test'));
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const errors = [];
  try {
    const page = await browser.newPage({ viewport: { width: 1536, height: 1000 } });
    page.on('pageerror', e => errors.push(e.message));
    await page.route('**/logo.png', r => r.fulfill({path: path.join(root,'frontend/dist/logo.png')}));
    await page.route('**/socket.io/**', r => r.abort());
    await page.route('**/chartink/api/search**', r => r.fulfill({json: {status:'success',data:[]}}));
    await page.goto('http://127.0.0.1:5011/portfolio');
    await expect(page.getByRole('heading', {name:'Investment Portfolio',exact:true})).toBeVisible();
    await page.getByRole('button', {name:'Add account',exact:true}).click();
    await page.getByLabel('Account name').fill('Browser verification');
    await page.getByRole('button', {name:'Save account',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('link', {name:'Stocks & ETFs',exact:true}).click();
    await page.getByRole('button', {name:'Add stock',exact:true}).click();
    await page.getByPlaceholder('Search symbol').fill('ATHER');
    await page.getByPlaceholder('Search symbol').press('Enter');
    await page.getByRole('button', {name:'Save stock',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('button', {name:'Record',exact:true}).click();
    await page.getByLabel('Trade date (IST)').fill('2026-09-01');
    await page.getByLabel('Quantity',{exact:true}).fill('100');
    await page.getByLabel('Price per unit (₹)').fill('1000');
    await page.getByRole('button', {name:'Record transaction',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.locator('tbody')).toContainText('₹1,00,000.00');
    await page.getByRole('button', {name:'Price',exact:true}).click();
    await page.getByLabel('Price (₹)',{exact:true}).fill('1100');
    await page.getByLabel('Price as of (IST)').fill('2026-10-01T15:30');
    await page.getByRole('button', {name:'Save valuation',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.locator('tbody')).toContainText('₹10,000.00');
    await page.getByRole('button', {name:'Record',exact:true}).click();
    await page.getByLabel('Action',{exact:true}).selectOption('SELL');
    await page.getByLabel('Quantity',{exact:true}).fill('101');
    await page.getByLabel('Price per unit (₹)').fill('1200');
    await page.getByRole('button', {name:'Record transaction',exact:true}).click();
    await expect(page.getByRole('alert')).toContainText('Sale exceeds');
    await page.getByLabel('Quantity',{exact:true}).fill('10');
    await page.getByRole('button', {name:'Record transaction',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.locator('tbody')).toContainText('₹90,000.00');
    await page.getByRole('button', {name:'History',exact:true}).click();
    await expect(page.getByRole('dialog').locator('tbody tr')).toHaveCount(2);
    await page.getByRole('dialog').getByRole('button', {name:'Close',exact:true}).click();
    await page.getByRole('navigation', {name:'Portfolio pages'}).getByRole('link', {name:'Dashboard',exact:true}).click();
    await expect(page.getByText('Weighted average, including charges',{exact:true})).toBeVisible();
    await expect(page.getByText('₹90,000.00',{exact:true})).toBeVisible();
    await expect(page.getByText('₹99,000.00',{exact:true})).toBeVisible();
    await expect(page.getByText('₹9,000.00',{exact:true})).toBeVisible();
    await expect(page.getByText('₹2,000.00',{exact:true})).toBeVisible();
    await page.getByLabel('Allocation basis').selectOption('market_value');
    await page.reload();
    await expect(page.getByText('₹90,000.00',{exact:true})).toBeVisible();
    const out=path.join(__dirname,'artifacts'); fs.mkdirSync(out,{recursive:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
    await page.screenshot({path:path.join(out,'dashboard-desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
    await page.screenshot({path:path.join(out,'dashboard-mobile.png'),fullPage:true});
    await page.getByRole('link',{name:'Stocks & ETFs',exact:true}).click();
    await expect(page.locator('tbody')).toContainText('₹90,000.00');
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
    await page.screenshot({path:path.join(out,'stocks-mobile.png'),fullPage:true});
    await page.setViewportSize({width:1536,height:1000});
    await page.getByRole('link',{name:'Other assets',exact:true}).click();
    await page.getByRole('button',{name:'Add asset',exact:true}).click();
    await page.getByLabel('Asset identifier',{exact:true}).fill('MF-TEST');
    await page.getByLabel('Scheme code',{exact:true}).fill('12345');
    await page.getByLabel('fund house',{exact:true}).fill('Fixture fund');
    await page.getByRole('button',{name:'Save asset',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('button',{name:'Record',exact:true}).click();
    await page.getByLabel('Trade date (IST)').fill('2026-09-01');
    await page.getByLabel('Quantity',{exact:true}).fill('1.123456');
    await page.getByLabel('Price per unit (₹)').fill('100');
    await page.getByRole('button',{name:'Record transaction',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.locator('tbody')).toContainText('1.123456');
    await page.getByText('Import dated prices / NAV from CSV',{exact:true}).click();
    await page.getByLabel('Price CSV',{exact:true}).fill('symbol,scheme_code,price,as_of\nMF-TEST,12345,110,2026-10-01T15:30:00+05:30');
    await page.getByRole('button',{name:'Import valuations',exact:true}).click();
    await expect(page.getByText('Imported 1 valuations.',{exact:true})).toBeVisible();
    await expect(page.locator('tbody')).toContainText('₹123.58');
    await page.getByLabel('Asset class',{exact:true}).selectOption('LOAN');
    await page.getByRole('button',{name:'Add asset',exact:true}).click();
    await page.getByLabel('Asset identifier',{exact:true}).fill('HOME-LOAN');
    await page.getByRole('button',{name:'Save asset',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('button',{name:'Record',exact:true}).click();
    await expect(page.getByRole('option',{name:'Borrow principal',exact:true})).toBeAttached();
    await page.getByLabel('Trade date (IST)').fill('2026-09-01');
    await page.getByLabel('Quantity',{exact:true}).fill('500');
    await page.getByLabel('Price per unit (₹)').fill('1');
    await page.getByRole('button',{name:'Record transaction',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('button',{name:'Price',exact:true}).click();
    await page.getByLabel('Price (₹)',{exact:true}).fill('1');
    await page.getByLabel('Price as of (IST)').fill('2026-10-01T15:30');
    await page.getByRole('button',{name:'Save valuation',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await expect(page.locator('tbody')).toContainText('-₹500.00');
    await page.reload();
    await expect(page.locator('tbody')).toContainText('HOME-LOAN');
    await page.getByRole('navigation',{name:'Portfolio pages'}).getByRole('link',{name:'Reports',exact:true}).click();
    const reportNames=['transactions','dividends','corporate-actions','performance','holdings','capital-gains','profit-loss','calendar','consolidated'];
    for(const name of reportNames){
      await page.getByLabel('Portfolio report').selectOption(name);
      await expect(page.getByRole('link',{name:'Download CSV'})).toHaveAttribute('href',new RegExp(`reports/${name}\\?`));
      await expect(page.getByText('Loading report…',{exact:true})).toHaveCount(0);
      await expect(page.getByRole('alert')).toHaveCount(0);
    }
    await page.getByLabel('Portfolio report').selectOption('capital-gains');
    await expect(page.locator('tbody')).toContainText('ATHER');
    await expect(page.getByText(/FIFO lot allocations/)).toBeVisible();
    const downloadPromise=page.waitForEvent('download');
    await page.getByRole('link',{name:'Download CSV'}).click();
    const download=await downloadPromise;
    await download.saveAs(path.join(out,'capital-gains.csv'));
    assert.match(fs.readFileSync(path.join(out,'capital-gains.csv'),'utf8'),/2000.0000/);
    await page.screenshot({path:path.join(out,'reports-desktop.png'),fullPage:true});
    await page.getByRole('link',{name:'Watchlists & paper GTT',exact:true}).click();
    await page.getByLabel('Watchlist name').fill('Long-term fixture');
    await page.getByRole('button',{name:'Create watchlist',exact:true}).click();
    await expect(page.getByLabel('Watchlist name')).toHaveValue('');
    await page.getByLabel('Selected watchlist').selectOption({label:'Long-term fixture · Long-term'});
    await page.getByLabel('Watch instrument').selectOption({label:'ATHER · Browser verification'});
    await page.getByLabel('Watch stop (optional)').fill('900');
    await page.getByLabel('Watch target (optional)').fill('1300');
    await page.getByRole('button',{name:'Add / update watch',exact:true}).click();
    await expect(page.getByRole('article')).toContainText('ATHER');
    await page.getByRole('button',{name:'Edit thresholds',exact:true}).click();
    await page.getByLabel('Watch target (optional)').fill('1000');
    await page.getByRole('button',{name:'Add / update watch',exact:true}).click();
    await expect(page.getByRole('article')).toContainText('at/above watch target');
    await page.getByText('Create a paper GTT for this category',{exact:true}).click();
    await expect(page.getByRole('button',{name:'Create paper GTT',exact:true})).toBeVisible();
    // Deliberately do not submit any order from the browser fixture.
    await expect(page.getByText('No portfolio paper triggers.',{exact:true})).toBeVisible();
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
    await page.screenshot({path:path.join(out,'watchlists-mobile.png'),fullPage:true});
    await page.getByRole('navigation',{name:'Portfolio pages'}).getByRole('link',{name:'Dashboard',exact:true}).click();
    await expect(page.getByText('₹98,623.58',{exact:true})).toBeVisible();
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
    await page.screenshot({path:path.join(out,'net-worth-mobile.png'),fullPage:true});
    assert.deepEqual(errors,[]);
    const result={passed:true, checked:['account and stock create','real CSRF-protected ledger purchase','manual dated price','oversell rejection and correction','partial sell WA/FIFO','persisted reload','dashboard reconciliation','cost/value chart switch','fractional mutual fund','CSV NAV import','liability borrowing and negative value','all nine reports','FIFO CSV download','watchlist create and thresholds edit','paper form without submission','mobile overflow'], expected:{quantity:90,cost:90000,value:99000,unrealized:9000,realized:2000,netWorth:98623.58},fixture:'isolated database; no operator data or orders',pageErrors:errors};
    fs.writeFileSync(path.join(out,'browser-verification.json'),JSON.stringify(result,null,2));
    console.log(JSON.stringify(result,null,2));
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1});
