const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=x=>x==null?'N/A':Number(x).toLocaleString('en-IN',{maximumFractionDigits:2}),money=x=>x==null?'N/A':'₹'+num(x);
const sign=x=>x<0?'negative':x>0?'positive':'',pf=r=>r.profit_factor_status==='no_losses'?'∞':r.profit_factor==null?'N/A':num(r.profit_factor);
let meta,report,periodPage=0,tradeOffset=0,requestSequence=0;
const layout={paper_bgcolor:'#101d30',plot_bgcolor:'#101d30',font:{color:'#b9cce5'},margin:{l:75,r:55,t:35,b:55},legend:{orientation:'h',y:1.14},xaxis:{type:'category',gridcolor:'#20334d'},yaxis:{gridcolor:'#20334d'},hovermode:'x unified'};
const options={responsive:true,displaylogo:false,toImageButtonOptions:{format:'png',width:1800,height:950,scale:2}};
function query(extra={}){return new URLSearchParams({strategy:$('strategy').value,path:$('path').value,start:$('from').value,end:$('to').value,group:$('group').value,...extra});}
async function api(route,q={}){const response=await fetch('/api/'+route+'?'+query(q));const value=await response.json();if(!response.ok)throw Error(value.error||'Request failed');return value;}
async function guarded(fn){$('error').textContent='';try{await fn();}catch(e){$('error').textContent=e.message;}}
function strategyOptions(){const selected=$('strategy').value,q=$('strategySearch').value.toLowerCase();$('strategy').innerHTML=meta.strategies.filter(r=>(r.id+' '+r.name).toLowerCase().includes(q)).map(r=>'<option value="'+r.id+'">'+esc(r.id+' · '+r.side+' '+r.minutes+'m · '+r.name)+'</option>').join('');if([...$('strategy').options].some(o=>o.value===selected))$('strategy').value=selected;}
function cards(r){const items=[
 ['Net P&L',money(r.net_pnl),'Return on reference capital: '+num(r.return_pct)+'%',sign(r.net_pnl)],
 ['Total trades',num(r.trades),num(r.filled_orders)+' filled orders, including partial exits'],
 ['Brokerage',money(r.brokerage),'All charges: '+money(r.fees)],
 ['Peak capital used',money(r.peak_capital),r.peak_capital_time||'No open positions'],
 ['Average capital used',money(r.average_capital),'Time-weighted over recorded sessions'],
 ['Maximum drawdown',money(r.max_drawdown),'Bar-close portfolio; spans days','negative'],
 ['Win rate',num(r.win_rate)+(r.win_rate==null?'':'%'),'Profit factor: '+pf(r)],
 ['Maximum open trades',num(r.max_open_trades),r.max_open_trades_time||'No trades'],
 ['Largest winning trade',money(r.max_win),'Net of modeled costs','positive'],
 ['Largest losing trade',money(r.max_loss),'Net of modeled costs','negative'],
 ['Average P&L / trade',money(r.average_trade_pnl),'Avg win '+money(r.average_win)+' / avg loss '+money(r.average_loss)],
 ['Reference capital',money(r.allocated_capital),'Cumulative entry notional: '+money(r.entry_notional)],
 ];$('cards').innerHTML=items.map(([label,value,hint,color])=>'<div class="card"><div class="label">'+label+'</div><div class="value '+(color||'')+'">'+value+'</div><div class="hint">'+esc(hint)+'</div></div>').join('');}
function periods(){const rows=report.periods.slice(periodPage*50,periodPage*50+50);$('periods').querySelector('tbody').innerHTML=rows.map(r=>'<tr><td>'+esc(r.period)+(r.partial?' <span class="muted">(partial)</span>':'')+'</td><td>'+r.days+'/'+r.planned_days+'</td><td>'+r.trades+'</td><td class="'+sign(r.net_pnl)+'">'+money(r.net_pnl)+'</td><td>'+money(r.brokerage)+'</td><td>'+money(r.fees)+'</td><td>'+money(r.peak_capital)+'</td><td>'+money(r.average_capital)+'</td><td>'+money(r.max_win)+'</td><td>'+money(r.max_loss)+'</td><td>'+num(r.win_rate)+'%</td><td>'+pf(r)+'</td><td>'+money(r.max_drawdown)+'</td><td>'+r.max_open_trades+'</td></tr>').join('');$('periodPage').textContent=' '+(periodPage+1)+' / '+Math.max(1,Math.ceil(report.periods.length/50))+' ';$('periodPrev').disabled=periodPage===0;$('periodNext').disabled=(periodPage+1)*50>=report.periods.length;}
async function refresh(){const seq=++requestSequence;if(!$('strategy').value)return;const result=await api('report');if(seq!==requestSequence)return;report=result;$('results').hidden=false;cards(report.summary);periodPage=0;periods();
 const c=report.curve;await Plotly.react('equityChart',[{name:'Closing cumulative net P&L',type:'scatter',mode:'lines',x:c.map(r=>r.day),y:c.map(r=>r.net_pnl),line:{color:'#4ade80'}},{name:'Drawdown at day close',type:'scatter',mode:'lines',x:c.map(r=>r.day),y:c.map(r=>r.drawdown_eod),line:{color:'#fb7185'}}],{...layout,yaxis:{...layout.yaxis,title:{text:'INR'}}},options);
 $('coverage').textContent=report.coverage.completed_days+' / '+report.coverage.planned_days+' planned sessions committed. '+report.coverage.skipped_symbol_sessions+' source stock-sessions skipped for data/metadata validation.';
 $('benchmark').textContent=report.benchmark.label+': '+(report.benchmark.available?num(report.benchmark.return_pct)+'% over selected sessions.':'unavailable for complete selected coverage. ')+report.benchmark.note;
 for(const [id,kind] of [['exportPeriods','periods'],['exportTrades','trades'],['exportFills','fills']])$(id).href='/api/export?'+query({kind});
 tradeOffset=0;await trades();const available=meta.days.filter(r=>r.day>=$('from').value&&r.day<=$('to').value);if(available.length){if(!available.some(r=>r.day===$('day').value))$('day').value=available[0].day;await inspect();}}
async function trades(){const data=await api('trades',{offset:tradeOffset,limit:50,symbol:$('stock').value.trim()});$('trades').querySelector('tbody').innerHTML=data.rows.map(t=>'<tr><td><a href="#" data-trade="'+esc(t.id)+'">Chart</a></td><td>'+t.day+'</td><td>'+esc(t.symbol)+'</td><td>'+t.side+'</td><td>'+t.quantity+'</td><td>'+new Date(t.entry_us/1000).toLocaleTimeString('en-GB',{timeZone:'Asia/Kolkata'})+'</td><td>'+new Date(t.exit_us/1000).toLocaleTimeString('en-GB',{timeZone:'Asia/Kolkata'})+'</td><td class="'+sign(t.net)+'">'+money(t.net)+'</td><td>'+money(t.brokerage)+'</td><td>'+money(t.fees)+'</td></tr>').join('');$('tradePage').textContent=' '+Math.min(tradeOffset+1,data.total)+'–'+Math.min(tradeOffset+50,data.total)+' / '+data.total+' ';$('tradePrev').disabled=tradeOffset===0;$('tradeNext').disabled=tradeOffset+50>=data.total;}
async function inspect(){if(!$('day').value)return;const [d,o]=await Promise.all([api('day',{day:$('day').value}),api('open',{day:$('day').value,at:$('at').value||'10:00:00'})]);$('openSummary').textContent=o.open_trades+' open trades · '+money(o.capital_used)+' capital in use · '+o.entries_so_far+' entries / '+o.closed_so_far+' closed so far · realized P&L less fees paid '+money(o.realized_pnl_less_paid_fees);$('openPositions').querySelector('tbody').innerHTML=o.positions.map(p=>'<tr><td><a href="#" data-trade="'+esc(p.id)+'">Chart</a></td><td>'+esc(p.symbol)+'</td><td>'+p.side+'</td><td>'+p.remaining+'</td><td>'+money(p.entry_price)+'</td><td>'+money(p.remaining*p.entry_price)+'</td></tr>').join('');
 const x=d.series.map(r=>r[0].slice(11,16));await Plotly.react('dayChart',[{name:'Capital (minute snapshots)',type:'scatter',mode:'lines',x,y:d.series.map(r=>r[2]),line:{color:'#38bdf8',shape:'hv'}},{name:'Open trades (minute snapshots)',type:'scatter',mode:'lines',x,y:d.series.map(r=>r[3]),yaxis:'y2',line:{color:'#fbbf24',shape:'hv'}}],{...layout,xaxis:{...layout.xaxis,title:{text:$('day').value+' · IST · exact-time lookup above'}},yaxis:{...layout.yaxis,title:{text:'Capital (INR)'}},yaxis2:{overlaying:'y',side:'right',title:{text:'Open trades'},rangemode:'tozero'}},options);
 $('quality').textContent=d.coverage.length?d.coverage.map(r=>r.symbol+' · '+r.status+' · '+r.details).join('\n'):'No committed session at this date. No results are assumed for missing sessions.';}
async function tradeChart(id){const {trade:t,candles:b,charts_stored}=await api('trade',{id});$('tradeTitle').textContent=t.symbol+' · '+t.side+' '+t.minutes+'m · '+t.day+' · '+t.scenario;$('tradeInfo').textContent='Net '+money(t.net_pnl)+' · fees '+money(t.fees)+' · modeled real-price fills. '+(charts_stored?'Green/red HA candles; raw candles can be toggled.':'Candle history was not stored for this run.');$('tradeDialog').showModal();
 const labels=b.map(r=>r.time.slice(11,16)),bucket=iso=>{const h=iso.slice(11,13),m=Math.floor(Number(iso.slice(14,16))/t.minutes)*t.minutes;return h+':'+String(m).padStart(2,'0');};
 const candle=(name,key,visible)=>({name,type:'candlestick',x:labels,open:b.map(r=>r[key][0]),high:b.map(r=>r[key][1]),low:b.map(r=>r[key][2]),close:b.map(r=>r[key][3]),visible,increasing:{line:{color:'#22c55e'},fillcolor:'#22c55e'},decreasing:{line:{color:'#ef4444'},fillcolor:'#ef4444'}});
 const traces=[candle('Heikin Ashi','ha',true),candle('Raw candles','raw','legendonly')];
 for(const [key,color] of [['bb_upper','#a78bfa'],['bb_mid','#718db4'],['bb_lower','#a78bfa'],['vwap','#f59e0b']])traces.push({type:'scatter',mode:'lines',name:key,x:labels,y:b.map(r=>r[key]),line:{color,width:1.3}});
 traces.push({type:'scatter',mode:'markers',name:'Entry',x:[bucket(t.entry_time)],y:[t.entry_price],marker:{symbol:t.side==='buy'?'triangle-up':'triangle-down',size:14,color:'#facc15'}});
 traces.push({type:'scatter',mode:'markers',name:'Exit fills',x:t.fills.slice(1).map(f=>bucket(f.time)),y:t.fills.slice(1).map(f=>f.price),text:t.fills.slice(1).map(f=>f.time+' '+f.reason),marker:{symbol:'x',size:12,color:'#fff'}});
 for(const [name,value,color] of [['Initial SL',t.initial_stop,'#fb7185'],['Target',t.target,'#4ade80']])traces.push({type:'scatter',mode:'lines',name,x:[bucket(t.entry_time),bucket(t.exit_time)],y:[value,value],line:{color,dash:'dash'}});
 if(t.stop_path.length)traces.push({type:'scatter',mode:'lines',name:'Trailing SL',x:t.stop_path.map(r=>bucket(r[0])),y:t.stop_path.map(r=>r[1]),line:{color:'#fb923c',shape:'hv'}});
 const categories=[];for(let i=555;i<=930;i+=t.minutes)categories.push(String(Math.floor(i/60)).padStart(2,'0')+':'+String(i%60).padStart(2,'0'));
 await Plotly.react('candleChart',traces,{...layout,margin:{l:75,r:40,t:70,b:60},xaxis:{type:'category',categoryarray:categories,categoryorder:'array',range:[-.5,categories.length-.5],rangeslider:{visible:false},tickmode:'array',tickvals:categories.filter((x,i)=>i===0||x.endsWith(':00')||x.endsWith(':30')),title:{text:'Full session 09:15–15:30 IST'}},yaxis:{...layout.yaxis,title:{text:'Price (INR)'}}},options);
 $('fills').querySelector('tbody').innerHTML=t.fills.map(f=>'<tr><td>'+f.time.slice(11,26).replace(/\+.*/,'')+'</td><td>'+f.side+'</td><td>'+f.reason+'</td><td>'+f.quantity+'</td><td>'+money(f.price)+'</td>'+['brokerage','exchange','sebi','stt','stamp','gst'].map(k=>'<td>'+money(f.costs[k])+'</td>').join('')+'<td>'+money(f.fees)+'</td></tr>').join('');}
document.addEventListener('click',e=>{const link=e.target.closest('[data-trade]');if(link){e.preventDefault();guarded(()=>tradeChart(link.dataset.trade));}});
$('closeTrade').onclick=()=>$('tradeDialog').close();$('refresh').onclick=()=>guarded(refresh);$('inspect').onclick=()=>guarded(inspect);$('strategySearch').oninput=strategyOptions;$('filterTrades').onclick=()=>{tradeOffset=0;guarded(trades);};$('tradePrev').onclick=()=>{tradeOffset=Math.max(0,tradeOffset-50);guarded(trades);};$('tradeNext').onclick=()=>{tradeOffset+=50;guarded(trades);};$('periodPrev').onclick=()=>{periodPage--;periods();};$('periodNext').onclick=()=>{periodPage++;periods();};$('group').onchange=()=>guarded(refresh);
guarded(async()=>{meta=await (await fetch('/api/meta')).json();const status=$('status');if(meta.state==='not_run'){status.className='notice empty-state';status.textContent=meta.message;$('empty').hidden=false;$('refresh').disabled=true;return;}const manifest=meta.manifest;status.className='notice '+(meta.state==='demo'?'demo':'');status.textContent=(meta.state==='demo'?'SYNTHETIC DEMO — artificial data; not historical performance. ':'')+(meta.state==='partial'?'PARTIAL RUN — ':'')+meta.days.length+' / '+manifest.planned_days.length+' sessions committed. '+(meta.state==='demo'?'Real 2017–2026 backtest has NOT run.':'OHLC-path approximation; inspect assumptions below.');strategyOptions();$('path').innerHTML=manifest.config.paths.map(p=>'<option>'+p+'</option>').join('');$('from').value=manifest.config.start;$('to').value=manifest.config.end;$('day').value=meta.days[0]?.day||manifest.config.start;$('assumptions').textContent=manifest.notes.join('\n')+'\nSlippage per fill: '+(manifest.config.slippage*100)+'%. Five-year anchor: '+manifest.config.five_year_anchor+'.\nFixed research fees: '+JSON.stringify(manifest.config.fixed_research_fees);await refresh();});
