const path=require('node:path');
const root=path.resolve(__dirname,'../..');
const {chromium,expect}=require(path.join(root,'frontend/node_modules/@playwright/test'));
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try {
 const page=await browser.newPage({viewport:{width:1536,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/socket.io/**',r=>r.abort());
 await page.goto('http://127.0.0.1:5011/portfolio');
 await expect(page.getByLabel('My accounts')).toContainText('Paper savings');
 await expect(page.getByLabel('My accounts')).not.toContainText('Live savings');
 await page.getByRole('navigation',{name:'Portfolio pages'}).getByRole('link',{name:'Stocks & ETFs'}).click();
 await expect(page.locator('tbody')).toContainText('300.00');
 await page.getByRole('button',{name:'Switch to Live mode',exact:true}).click();
 await expect(page.getByLabel('My accounts')).toContainText('Live savings');
 await expect(page.getByLabel('My accounts')).not.toContainText('Paper savings');
 await expect(page.locator('tbody')).toContainText('700.00');
 await page.getByRole('link',{name:'Watchlists & orders',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Live orders · fyers'})).toBeVisible();
 await expect(page.getByText('Portfolio paper triggers',{exact:true})).toHaveCount(0);
 await page.getByLabel('Order instrument').selectOption({label:'SBIN · Live savings'});
 await page.getByLabel('Order quantity').fill('2');
 await page.getByLabel('Order limit price').fill('100');
 await page.getByRole('button',{name:'Review Live order',exact:true}).click();
 await expect(page.getByRole('button',{name:'Confirm Live order',exact:true})).toBeVisible();
 await page.screenshot({path:path.join(__dirname,'artifacts/live-order-review-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'Confirm Live order',exact:true}).click();
 await expect(page.getByText(/accepted · FIXTURE-ORDER/)).toBeVisible();
 await expect(page.getByRole('button',{name:'Confirm Live order',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'Switch to Analyze mode',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Sandbox orders · fyers'})).toBeVisible();
 await expect(page.getByLabel('Order quantity')).toHaveValue('');
 await expect(page.getByText('FIXTURE-ORDER',{exact:true})).toHaveCount(0);
 await expect(page.getByText('Portfolio paper triggers',{exact:true})).toBeVisible();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(__dirname,'artifacts/sandbox-orders-mobile.png'),fullPage:true});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('Mobile overflow');
 await page.goto('http://127.0.0.1:5011/strategy-reports');
 await expect(page.getByLabel('Execution scenario')).toHaveValue('PAPER');
 await page.getByRole('button',{name:'Switch to Live mode',exact:true}).click();
 await expect(page.getByLabel('Execution scenario')).toHaveValue('LIVE');
 await page.goto('http://127.0.0.1:5011/market-scanner');
 await expect(page.getByText('Live · Live broker market data in both modes')).toBeVisible();
 await page.getByRole('button',{name:'Switch to Analyze mode',exact:true}).click();
 await expect(page.getByText('Sandbox · Live broker market data in both modes')).toBeVisible();
 if(errors.length)throw Error(errors.join('\n'));
 console.log(JSON.stringify({portfolio_mode_separation:true,live_review_and_mock_dispatch:true,mode_clears_forms:true,journal_mode:true,screener_both_modes:true,mobile_no_overflow:true,errors,broker_calls:0}));
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
