const path = require('node:path');
const fs = require('node:fs');
const root = path.resolve(__dirname, '../..');
const { chromium, expect } = require(path.join(root, 'frontend/node_modules/@playwright/test'));
if (process.argv.includes('--modes')) require('./verify_modes.cjs');
else (async () => {
  const browser = await chromium.launch({channel:'chrome',headless:true});
  try {
    const page = await browser.newPage({viewport:{width:1920,height:1080}});
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto('http://127.0.0.1:5011/strategy-reports');
    await expect(page.getByRole('heading',{name:'Strategy Reports',exact:true})).toBeVisible();
    await expect(page.getByText('FY net')).toBeVisible();
    await expect(page.getByLabel('Charges basis')).toHaveValue('estimated');
    await expect(page.getByText('FYERS standard',{exact:false}).first()).toBeVisible();
    await page.getByRole('button',{name:/07 October 2026:/}).click();
    await expect(page.getByRole('heading',{name:'07 October 2026'})).toBeVisible();
    await expect(page.getByText('2 strategies · Combined daily performance')).toBeVisible();
    const out=path.join(__dirname,'artifacts');fs.mkdirSync(out,{recursive:true});
    await page.screenshot({path:path.join(out,'calendar-desktop.png'),fullPage:true});
    await page.locator('summary').filter({hasText:'Nifty500 Fixed 3R'}).click();
    await expect(page.getByRole('button',{name:'View strategy calendar'}).first()).toBeVisible();
    await page.getByRole('button',{name:'Open individual trades & charts'}).click();
    await expect(page.getByRole('link',{name:'Download trades CSV'})).toBeVisible();
    await expect(page.getByLabel('Trade chart',{exact:true})).toBeVisible();
    await expect(page.locator('svg[role="img"]')).toHaveCount(1);
    await expect(page.locator('svg polyline')).toHaveCount(3);
    await page.getByLabel('Heikin Ashi candles').check();
    await page.getByLabel('Full session').check();
    await page.screenshot({path:path.join(out,'strategy-detail-desktop.png'),fullPage:true});
    await page.getByRole('button',{name:'View strategy calendar'}).click();
    await expect(page.getByLabel('Strategy filter')).toHaveValue('fixed');
    await page.getByLabel('Stock filter').selectOption('SBIN');
    await expect(page.getByText('1 strategies · Combined daily performance')).toBeVisible();
    await page.getByRole('button',{name:'Daily list',exact:true}).click();
    await expect(page.getByRole('button',{name:/07 October 2026.*1 strategies/})).toBeVisible();
    await page.screenshot({path:path.join(out,'daily-list-desktop.png'),fullPage:true});
    await page.getByRole('button',{name:'Clear filters'}).click();
    await page.getByRole('button',{name:'Calendar',exact:true}).click();
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:path.join(out,'calendar-mobile.png'),fullPage:true});
    if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)) throw Error('Mobile page overflow');
    await page.locator('summary').filter({hasText:'Nifty500 Fixed 3R'}).click();
    await page.screenshot({path:path.join(out,'strategy-mobile.png'),fullPage:true});
    if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)) throw Error('Expanded mobile overflow');
    await page.getByLabel('Charges basis').selectOption('recorded');
    await expect(page.getByLabel('Charges basis')).toHaveValue('recorded');
    await page.getByLabel('Charges basis').selectOption('estimated');
    await page.getByRole('button',{name:'Previous financial year'}).click();
    await expect(page.getByRole('heading',{name:'2025–2026',exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Daily list',exact:true}).click();
    await expect(page.getByText('No reports for these filters in this financial year.')).toBeVisible();
    if(errors.length) throw Error(errors.join('\n'));
    console.log(JSON.stringify({desktop:true,mobile:true,filters:true,individual_trades:true,empty_year:true,errors,source:'synthetic isolated preview on 5011'}));
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
