const path=require('node:path'),fs=require('node:fs');const root=path.resolve(__dirname,'../..');
const {chromium,expect}=require(path.join(root,'frontend/node_modules/@playwright/test'));
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1512,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5011/logs/latency');
 await expect(page.getByRole('heading',{name:'Request Latency Monitor'})).toBeVisible();
 await expect(page.getByText('125 successful · 5 failed · 0 partial')).toBeVisible();
 await expect(page.getByText('84.0%',{exact:true}).first()).toBeVisible();
 await expect(page.getByText('100 displayed · time in IST')).toBeVisible();
 const out=path.join(root,'log/test/latency/screenshots');fs.mkdirSync(out,{recursive:true});
 await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});
 await page.getByLabel('Request category').selectOption('data');
 await expect(page.getByText('12 successful · 0 failed · 0 partial')).toBeVisible();
 await page.getByRole('button',{name:'Details',exact:true}).first().click();
 await expect(page.getByText(/Historical attribution is uncertain/)).toBeVisible();
 await page.keyboard.press('Escape');
 await page.getByLabel('Mode at request').selectOption('live');
 await expect(page.getByText('No matching requests. Select Data & account reads or a wider period to inspect history.')).toBeVisible();
 await page.getByLabel('Request category').selectOption('orders');
 await page.getByLabel('Mode at request').selectOption('sandbox');
 await expect(page.getByText('125 successful · 0 failed · 0 partial')).toBeVisible();
 await page.getByRole('button',{name:'Details',exact:true}).first().click();
 await expect(page.getByText('Captured HTTP calls',{exact:true})).toBeVisible();
 await page.keyboard.press('Escape');
 const href=await page.getByRole('link',{name:'Export CSV'}).getAttribute('href');
 if(!href.includes('kind=orders')||!href.includes('mode=sandbox'))throw Error('Export lost filters');
 const response=await page.request.get('http://127.0.0.1:5011'+href);const csv=await response.text();if(csv.split('\n').filter(Boolean).length!==126)throw Error('CSV did not export all filtered rows');
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('Mobile overflow');
 await page.route('**/latency/api/dashboard?**',route=>route.fulfill({status:500,contentType:'application/json',body:'{"error":"test failure"}'}));
 await page.getByRole('button',{name:'Refresh',exact:true}).click();
 await expect(page.getByRole('alert')).toContainText('Could not refresh latency data',{timeout:15000});
 if(errors.length)throw Error(errors.join('\n'));
 console.log(JSON.stringify({desktop:true,mobile:true,consistentStats:true,filters:true,unknownLegacy:true,details:true,csv:true,errorState:true,jsErrors:[]}));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
